# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: ruby:2.7.0-alpine3.11

stages:
  - test

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby


before_script:
  - ruby -v  # Print out ruby version for debugging
  - apk add --update build-base postgresql-dev
  - gem install bundler -v '>= 2.1.4'
  - bundle config set path /tmp/vendor # Install dependencies into ./vendor/ruby
  - bundle install -j $(nproc)

rubocop:
  stage: test
  script:
    - rubocop
