# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
default:
  image: ruby:2.7.0-alpine3.11

variables:
  POSTGRES_DB:               tcelfer_dev
  POSTGRES_USER:             tcelfer_dev
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

rubocop:
  stage: test
  before_script:
    - sh .ci/before-script.sh
  script:
    - bundle exec rubocop

api_console:
  services:
    - postgres:12.2-alpine
  stage: test
  before_script:
    # This is all very messy for now. Sorry
    - sh .ci/before-script.sh
    - sh .ci/init-tcelfer-db.sh
    - bundle exec puma&
    - sleep 10
  script:
    - zsh .ci/test_user_gen.zsh
    - kill $(jobs -p)
