Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/LineLength:
  Max: 120

AllCops:
  Exclude:
      - 'tmp/*'
  TargetRubyVersion: 2.6
