Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 120

AllCops:
  Exclude:
      - 'tmp/*'
  TargetRubyVersion: 2.6

# These are new in Rubocop 0.80.0
# Which now will start introducing things in this manor
# see https://github.com/rubocop-hq/rubocop/issues/7731 for more info
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
