Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

AllCops:
  Exclude:
      - 'tmp/*'
      - 'vendor/**/*'
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
