tokens:
  valid_for: 3600 # 1 hour
  refresh_valid_for: 86_400 # 1 day
db_conf:
  host: postgres
  user: tcelfer_dev
  database: tcelfer_dev
  # password: hunter2
cors:
  debug: true
  remote_hosts:
    - http://localhost:8080
